# Generated by Django 5.1.6 on 2025-03-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applicant',
            new_name='StaffDetails',
        ),
    ]
