# Generated by Django 5.1.6 on 2025-03-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0002_rename_applicant_staffdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='job_applied',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
