# Generated by Django 5.1.6 on 2025-03-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0003_alter_staffdetails_job_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='confirm_password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
