# Generated by Django 5.1.6 on 2025-03-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0006_alter_staffdetails_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='applicants/certificates/'),
        ),
    ]
