# Generated by Django 5.1.6 on 2025-03-04 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0007_alter_staffdetails_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdetails',
            name='certificate',
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='applicants/certificates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='careapp.staffdetails')),
            ],
        ),
    ]
