# Generated by Django 5.1.6 on 2025-03-05 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0008_remove_staffdetails_certificate_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='file',
            new_name='certificate',
        ),
    ]
